-- phpMyAdmin SQL Dump
-- version 5.2.1
-- https://www.phpmyadmin.net/
--
-- Host: 127.0.0.1
-- Tempo de geração: 26/06/2024 às 17:51
-- Versão do servidor: 10.4.32-MariaDB
-- Versão do PHP: 8.2.12

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
START TRANSACTION;
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Banco de dados: `repositorio_base`
--

-- --------------------------------------------------------

--
-- Estrutura para tabela `posts`
--

CREATE TABLE `posts` (
  `id` int(11) NOT NULL,
  `title` varchar(255) NOT NULL,
  `image` varchar(255) NOT NULL,
  `content` text NOT NULL,
  `author` varchar(255) NOT NULL,
  `date` date NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

--
-- Despejando dados para a tabela `posts`
--

INSERT INTO `posts` (`id`, `title`, `image`, `content`, `author`, `date`) VALUES
(1, 'Batalhas Épicas em um Mundo em Constante Mudança', 'public/img/667c34756aa6b.jpeg', 'Nos confins de um mundo virtual vibrante e dinâmico, onde a habilidade e a estratégia se encontram, surge Fortnite. Um campo de batalha onde a criatividade encontra a competição, e cada partida é uma nova aventura em busca da vitória suprema.\r\nEm uma ilha repleta de paisagens variadas, desde florestas exuberantes até desertos áridos, jogadores de todas as partes do mundo se reúnem para competir em uma luta pela sobrevivência. Armados com uma variedade de armas e habilidades únicas, cada um busca ser o último em pé em um turbilhão de ação implacável.\r\nFortnite não é apenas um jogo de tiros, é um campo de jogo onde a construção rápida e estratégica é tão vital quanto a precisão do tiro. Torres e rampas surgem em questão de segundos, transformando o campo de batalha e criando oportunidades táticas que podem mudar o curso de uma partida em um instante.\r\nMas Fortnite vai além do combate. É um universo em constante evolução, onde eventos épicos transformam a paisagem e novas histórias se desenrolam a cada temporada. Heróis e vilões emergem, mitos são criados e mistérios são revelados, tudo enquanto os jogadores exploram, enfrentam desafios e desbloqueiam recompensas exclusivas.\r\nCada partida é uma oportunidade para mostrar habilidade, estratégia e criatividade. Seja sozinho, em dupla ou em equipe, os jogadores testam seus limites em modos competitivos ou se unem em missões cooperativas, cada um buscando a glória em suas próprias jornadas épicas.\r\nE enquanto o mundo real assiste, Fortnite transcende o jogo para se tornar um fenômeno cultural. De danças icônicas a eventos ao vivo que capturam a imaginação de milhões, Fortnite se tornou mais do que um jogo; é um meio de expressão, um campo de experimentação e um ponto de encontro para uma comunidade global.\r\nAssim, em meio aos gráficos vívidos, à trilha sonora pulsante e à constante evolução do mundo de Fortnite, os jogadores encontram não apenas competição, mas também camaradagem, criatividade e a emoção de uma jornada que nunca para de surpreender.', 'José Pereira Santos', '2024-06-04'),
(2, 'A Ascensão da Sombra na Terra de Pharloom', 'public/img/667c352595c75.jpeg', 'Em um reino vasto e encantador, mergulhado em mistérios e perigos, emerge a história de Silksong. Neste conto épico, você é conduzido através de paisagens exuberantes e sombrias, guiado por uma heroína destemida, Hornet, em sua jornada para desvendar os segredos de Pharloom.\r\nPharloom se estende em todas as direções, um mundo de beleza e trevas onde criaturas exóticas e desafios iminentes aguardam a intrépida Hornet. Armada com agilidade e uma agulha afiada, ela enfrenta adversários formidáveis e labirintos intricados que testam não apenas suas habilidades de combate, mas também sua perspicácia e coragem.\r\nCada passo em Pharloom revela uma história nova e intrigante, desde encontros com personagens enigmáticos até confrontos com chefes épicos que desafiam a própria definição de poder e astúcia. A trilha sonora melancólica ecoa pelos vales e cavernas, adicionando uma camada de profundidade emocional à busca incansável de Hornet por respostas.\r\nMas em meio às sombras de Pharloom, também há beleza indescritível: os jardins suspensos, as cidades abandonadas e as paisagens oníricas que são tanto uma maravilha quanto um desafio para os exploradores destemidos. Cada novo cenário revela pistas sobre o passado enigmático deste reino desconhecido.\r\nSilksong não é apenas uma continuação, é uma evolução do legado de Hollow Knight, levando os jogadores a novas alturas de exploração e descoberta. Com mecânicas de jogo refinadas e novas habilidades para dominar, cada desafio é uma oportunidade para crescer e se adaptar em um ambiente que está sempre mudando.\r\nEm última análise, Silksong é uma saga de determinação e triunfo sobre a adversidade, onde a força da vontade e a curiosidade inabalável de Hornet a levam a explorar os limites de Pharloom e a descobrir seu lugar neste reino de maravilhas e mistérios.', 'Débora Ribeiro Nunes', '2024-06-07'),
(3, 'Skyrim: A Saga Épica de Dragões e Destino', 'public/img/667c355b5e33c.jpeg', 'Nos vastos e gelados territórios de Skyrim, um mundo repleto de lendas antigas e mistérios ocultos aguarda aqueles corajosos o suficiente para explorá-lo. Nesta terra de picos nevados e florestas densas, onde a magia e a espada se encontram, emerge uma jornada épica que redefine o conceito de aventura.\r\nNo papel do Dovahkiin, o Dragão Nascido, os jogadores são imersos em uma narrativa rica que entrelaça escolhas morais, conflitos políticos e a luta contra uma ameaça ancestral: os dragões. Dotado de poderes draconianos e destinado a enfrentar Alduin, o Devorador de Mundos, o Dovahkiin deve dominar habilidades de combate e magia para desvendar os segredos de seu próprio destino.\r\nSkyrim não é apenas um lugar para explorar; é um mundo vivo e respirante, povoado por personagens marcantes, desde nobres nobres até bandidos astutos. Cada cidade e vila tem sua própria história para contar, suas próprias rivalidades e alianças, criando um ambiente dinâmico onde as decisões dos jogadores moldam o curso dos acontecimentos.\r\nAlém da vastidão de Skyrim, seus dungeons labirínticos e ruínas antigas oferecem desafios para aqueles que procuram tesouros escondidos e conhecimentos esquecidos. Criaturas místicas, como os temíveis Draugr e os enigmáticos Falmer, espreitam nas sombras, prontas para desafiar a bravura dos aventureiros.\r\nA trilha sonora épica e as paisagens impressionantes contribuem para uma imersão total, transportando os jogadores para um mundo onde as montanhas ecoam com o rugido dos dragões e as florestas sussurram segredos antigos.\r\nEm resumo, Skyrim não é apenas um jogo, mas uma experiência que transcende os limites do RPG tradicional. Com sua narrativa envolvente, liberdade de exploração e a promessa de descobertas constantes, Skyrim continua a capturar a imaginação de gerações de jogadores, lembrando a todos que o verdadeiro poder reside naqueles que ousam desbravar o desconhecido e moldar o próprio destino.', 'Sara Mendes Garcia', '2024-06-07'),
(4, 'A Jornada Emocional de um Espírito no Mundo de Nibel', 'public/img/667c359f31dc9.jpeg', 'Em um mundo onde a beleza natural se mistura com a escuridão iminente, Ori oferece uma jornada emocional que encanta e desafia os jogadores. No papel de Ori, um pequeno espírito guardião, os jogadores exploram o vibrante e perigoso mundo de Nibel, repleto de mistérios antigos e criaturas místicas.\r\nA história de Ori é uma ode à amizade e ao sacrifício, enquanto ele busca restaurar a luz e a vida em um reino à beira do colapso. Ao longo do caminho, Ori encontra Sein, uma entidade espiritual que se torna sua guia e companheira na busca pela cura de Nibel.\r\nA jogabilidade de Ori combina habilidades ágeis de plataforma com quebra-cabeças desafiadores e encontros de combate emocionantes. Ori pode desbloquear novas habilidades e poderes ao longo da jornada, permitindo acesso a áreas anteriormente inacessíveis e enfrentando desafios cada vez maiores.\r\nAlém da mecânica de jogo envolvente, Ori é uma experiência visual deslumbrante. Os gráficos pintados à mão e a trilha sonora arrebatadora criam um ambiente imersivo que evoca uma gama completa de emoções, desde a tranquilidade dos bosques serenos até a tensão dos confrontos épicos.\r\nMais do que um jogo de plataforma, Ori é uma narrativa visual que celebra a conexão entre os seres vivos e o poder da esperança em face da adversidade. Cada descoberta em Nibel revela novas camadas de sua história rica e complexa, alimentando o desejo de explorar cada canto do mundo maravilhosamente criado.\r\nEm resumo, Ori não é apenas uma aventura; é uma experiência poética que ressoa com sua beleza visual e profundidade emocional. Com uma narrativa que transcende as palavras e uma jogabilidade que desafia e recompensa, Ori continua a conquistar o coração dos jogadores como um testemunho da magia dos jogos indie e da criatividade ilimitada dos desenvolvedores.', 'Débora Ribeiro Nunes', '2024-06-08'),
(5, 'Um Épico de Fantasia e Aventura', 'public/img/667c35f47dd8c.jpeg', 'Desde suas origens humildes até se tornar um ícone do RPG japonês, Final Fantasy continua a cativar jogadores ao redor do mundo com sua narrativa envolvente, personagens memoráveis e mundos vastos e ricos.\r\nCada jogo da série Final Fantasy é uma jornada única e emocionante, repleta de heróis destinados, vilões implacáveis e magias poderosas. Desde os campos verdejantes de Midgar até os céus de Cocoon, os jogadores são transportados para universos onde a magia e a tecnologia coexistem, e onde os destinos se cruzam em batalhas épicas pelo equilíbrio do mundo.\r\nA história de cada Final Fantasy é tecida com temas profundos de amor, coragem, sacrifício e redenção, enquanto os protagonistas se encontram em uma luta constante contra forças obscuras que ameaçam consumir tudo que conhecem. As reviravoltas na trama, os momentos emocionantes e as decisões impactantes fazem com que cada jogo seja uma experiência emocionalmente rica e memorável.\r\nAlém da narrativa envolvente, a série Final Fantasy é conhecida por seu sistema de combate estratégico e inovador. Desde a escolha das habilidades dos personagens até a gestão de recursos e a formação de equipes, cada batalha oferece um desafio que exige planejamento cuidadoso e execução precisa.\r\nOs mundos de Final Fantasy são tão ricos em detalhes quanto visualmente deslumbrantes, com paisagens variadas que vão desde cidades movimentadas até cavernas misteriosas e templos antigos. A trilha sonora envolvente e os gráficos impressionantes elevam a imersão, transportando os jogadores para terras distantes e emocionantes aventuras.\r\nAlém dos elementos de jogo, Final Fantasy transcende o entretenimento para se tornar uma parte da cultura popular global. Desde músicas icônicas até personagens emblemáticos que se tornam ícones, a série deixa uma marca indelével no coração dos fãs que continuam a celebrar e reviver suas experiências favoritas ao longo dos anos.\r\nEm suma, Final Fantasy não é apenas uma série de jogos; é uma saga que captura a imaginação e emociona os jogadores com sua profundidade emocional, desafios estratégicos e mundos maravilhosamente concebidos. A cada novo capítulo, a série prova que a magia do RPG continua viva e pronta para desafiar e inspirar novas gerações de jogadores.', 'Cristiano Matos Cardoso', '2024-06-14'),
(6, 'Explorando a Vida no Mundo Aberto de Crime e Oportunidades', 'public/img/667c3630cf30a.jpeg', 'Nos becos sombrios e arranha-céus imponentes de Liberty City, Los Santos ou Vice City, Grand Theft Auto (GTA) oferece uma experiência de jogo única e envolvente onde os jogadores podem mergulhar em um mundo de crime, poder e intriga.\r\nEm cada iteração da série GTA, os jogadores assumem o papel de protagonistas ambiciosos, muitas vezes anti-heróis, que buscam ascender nas fileiras do submundo criminoso. Desde pequenos delitos até assaltos elaborados e conspirações globais, GTA coloca os jogadores no centro de ações ousadas e decisões morais complexas.\r\nA liberdade é a essência de GTA, com vastos mundos abertos que convidam à exploração. Cidades vibrantes são recriadas com detalhes impressionantes, desde a movimentada vida urbana até as paisagens rurais serenas, cada uma oferecendo atividades diversificadas e oportunidades para o caos ou o sucesso.\r\nAlém da jogabilidade principal, GTA é conhecido por sua narrativa envolvente e personagens cativantes. Através de missões intricadas e diálogos afiados, os jogadores são levados a um universo onde a ambição, a ganância e o desejo de poder moldam destinos e determinam quem sai por cima na selva de concreto.\r\nA série também é um reflexo satírico da cultura contemporânea, com humor mordaz e críticas sociais misturadas ao jogo. Desde rádios piratas e propagandas bizarras até paródias de figuras públicas e celebridades, GTA cria um espelho distorcido do mundo real onde o absurdo e o drama se encontram.\r\nAlém disso, GTA é um playground para a criatividade dos jogadores. Modos online permitem que amigos se reúnam para missões cooperativas ou competições frenéticas, enquanto ferramentas de criação permitem que os jogadores personalizem e compartilhem seus próprios conteúdos dentro do universo do jogo.\r\nEm resumo, GTA é mais do que um jogo de ação e crime; é uma experiência cultural que desafia as convenções e expande os limites do que é possível em um jogo de mundo aberto. Com sua mistura única de narrativa envolvente, jogabilidade dinâmica e sátira afiada, GTA continua a ser uma das séries mais impactantes e populares na história dos videogames.', 'Jonas Espíndola', '2024-06-16'),
(7, 'Uma Aventura Alucinante pelo Mundo das Animações Clássicas', 'public/img/667c368675180.jpeg', 'Em um mundo onde o estilo dos desenhos animados dos anos 1930 ganha vida, Cuphead oferece uma experiência de jogo única e desafiadora. Com seu visual vibrante e inspirado nas animações da era de ouro da animação, o jogo mergulha os jogadores em uma jornada épica através de cenários surrealistas e encontros com chefes tão criativos quanto desafiadores.\r\nNo papel de Cuphead ou Mugman (ou ambos, no modo cooperativo), os jogadores embarcam em uma missão desesperada para pagar uma dívida com o diabo. Cada fase é uma obra de arte meticulosamente desenhada à mão, repleta de inimigos peculiares e enigmas intrincados que testam reflexos e habilidades estratégicas.\r\nA jogabilidade de Cuphead é intensamente focada em combates de chefes, cada um mais elaborado do que o anterior. Cada confronto é uma dança coreografada de ataques precisos e evasões ágeis, com padrões de movimento que desafiam os jogadores a aprender e adaptar suas estratégias.\r\nAlém do desafio, Cuphead é uma celebração da arte da animação, com uma trilha sonora de jazz frenética que complementa perfeitamente a ação na tela. Cada personagem, de personagens secundários a chefes principais, é trazido à vida com um estilo visual e uma personalidade únicos, evocando nostalgia e admiração por igual.\r\nAo longo da jornada, os jogadores descobrem novas habilidades e power-ups que ampliam suas capacidades, permitindo novas abordagens para enfrentar desafios antigos. A progressão é recompensadora, com cada vitória não apenas avançando na narrativa, mas também desbloqueando novos aspectos do mundo exuberante de Cuphead.\r\nEm resumo, Cuphead não é apenas um jogo, é uma homenagem apaixonada aos primórdios da animação e uma experiência de jogo que desafia e encanta. Com sua estética visual distintiva e jogabilidade envolvente, continua a cativar jogadores de todas as idades, oferecendo uma experiência única e memorável que transcende as fronteiras entre arte e entretenimento digital.', 'Cristiano Matos Cardoso', '2024-06-21'),
(8, 'O Palco Global do Futebol Virtual', 'public/img/667c36b77208e.jpeg', 'Nos campos virtuais do FIFA, o mundo do futebol ganha vida de uma forma única e emocionante. Cada partida é uma celebração do esporte mais popular do planeta, onde jogadores de todos os cantos do globo competem para alcançar a glória nos gramados virtuais.\r\nCom uma precisão impressionante, FIFA captura não apenas a física realista do jogo, mas também a emoção intensa que acompanha cada passe, chute e defesa. Desde os movimentos elegantes dos jogadores até os estádios icônicos que ecoam com os cânticos das torcidas, cada detalhe é meticulosamente recriado para transportar os jogadores para o coração do jogo.\r\nMas FIFA vai além do jogo simples; é uma experiência imersiva que se estende além do campo. Modos de jogo variados oferecem desde partidas rápidas e desafiadoras até campanhas extensas que permitem aos jogadores construir e gerenciar suas próprias equipes. A estratégia fora do campo é tão crucial quanto a habilidade dentro dele, com a personalização de táticas e formações moldando o curso de cada partida.\r\nE o mundo do FIFA não conhece fronteiras. Milhões de jogadores competem online, testando suas habilidades em partidas classificatórias, torneios globais e ligas personalizadas. Amigos se tornam rivais e adversários se tornam aliados, tudo em busca da supremacia nos rankings mundiais.\r\nAlém disso, FIFA é um portal para o mundo do futebol real. Atualizações frequentes refletem as mudanças no esporte, incluindo novas transferências de jogadores, uniformes atualizados e eventos sazonais que mantêm o jogo tão dinâmico quanto o esporte que o inspira.\r\nEm cada jogo, FIFA é mais do que apenas uma simulação; é uma celebração do espírito competitivo e da paixão pelo futebol. Seja competindo localmente com amigos ou enfrentando adversários globais, os jogadores encontram um terreno comum onde a habilidade e a estratégia se encontram, criando momentos memoráveis e histórias emocionantes a cada partida.\r\nAssim, dentro dos gramados virtuais do FIFA, o jogo se torna um reflexo do esporte real: um palco global onde os sonhos se realizam, as rivalidades se intensificam e os heróis são feitos.', 'Vanessa Soares', '2024-06-21'),
(9, 'Em Busca de Respostas nas Profundezas de Hallownest', 'public/img/667c370b98f8d.jpeg', 'Em meio às sombras e mistérios de Hallownest, uma terra vasta e antiga, onde ruínas esquecidas e criaturas estranhas se entrelaçam, uma figura solitária avança com determinação. Armado apenas com uma espada afiada e uma coragem inabalável, o Cavaleiro Vazio explora cada canto escuro e cada recanto oculto deste reino subterrâneo.\r\nHallownest, uma civilização caída, agora encontra-se mergulhada em um silêncio profundo, interrompido apenas pelo eco distante de seus habitantes perdidos. O Cavaleiro Vazio, sem memória de seu passado, é a única esperança para desvendar os segredos enterrados nas profundezas de Hallownest e descobrir sua própria origem.\r\nCada passo adiante é uma batalha contra adversários formidáveis: insetos corrompidos, guerreiros esqueletos e criaturas sombrias que guardam seus segredos com ferocidade. No entanto, cada vitória traz uma peça do quebra-cabeça, revelando fragmentos da história de Hallownest e guiando o Cavaleiro em direção ao seu destino.\r\nMas não são apenas desafios físicos que aguardam o Cavaleiro Vazio. Enigmas intricados e quebra-cabeças desafiadores bloqueiam seu caminho, exigindo não apenas habilidade de combate, mas também astúcia e perseverança. A jornada é uma dança entre o perigo iminente e a exploração cuidadosa, cada passo um lembrete da vastidão e complexidade deste reino subterrâneo.\r\nNo entanto, em meio às trevas, há beleza. A arte meticulosa que adorna cada câmara antiga, a trilha sonora melancólica que ecoa pelos salões vazios e os encontros com personagens misteriosos que oferecem ajuda ou obstáculos – todos contribuem para a rica tapeçaria de Hallownest.\r\nO Cavaleiro Vazio avança, não apenas em busca de respostas sobre seu próprio passado, mas também em um esforço para restaurar o que foi perdido em Hallownest. Cada descoberta, cada confronto e cada mistério desvendado trazem o Cavaleiro mais perto de compreender seu propósito neste reino condenado.\r\nEm Hallownest, a jornada do Cavaleiro Vazio é não apenas uma busca por conhecimento e poder, mas uma exploração emocional e espiritual que desafia tanto a mente quanto o corpo. E assim, nas profundezas escuras e nas alturas perdidas de Hallownest, o Cavaleiro Vazio segue adiante, determinado a encontrar não apenas respostas, mas também redenção e um lugar neste mundo vasto e enigmático.', 'Débora Ribeiro Nunes', '2024-06-26'),
(10, 'Entre Espadas e Feitiçarias em um Mundo de Intrigas', 'public/img/667c372aa1f3e.jpeg', 'Nas terras vastas e turbulentas do Continente, um caçador de monstros singular percorre caminhos tortuosos e enfrenta perigos inimagináveis. Geralt de Rivia, o bruxo conhecido por sua habilidade com a espada e seu conhecimento profundo de magia, é o protagonista de uma saga épica que mistura fantasia sombria, política intrincada e dilemas morais complexos.\r\nEm um mundo onde humanos, elfos, anões e outras criaturas míticas coexistem com desconfiança e conflito, Geralt navega pelas camadas de intrigas palacianas, enfrentando criaturas sobrenaturais que assolam vilarejos despreparados. Cada missão, cada contrato de monstro, não apenas testa suas habilidades de combate, mas também desafia suas convicções éticas e seus relacionamentos pessoais.\r\nO Continente é um lugar de beleza selvagem e escuridão insondável, onde as decisões de Geralt moldam não apenas seu próprio destino, mas também o curso de reinos inteiros. Alianças voláteis, traições astutas e segredos antigos permeiam cada cidade fortificada e cada bosque sombrio, criando um cenário de constantes reviravoltas e surpresas.\r\nAlém dos perigos físicos, Geralt também enfrenta desafios emocionais profundamente arraigados. Seu relacionamento com Yennefer, uma feiticeira igualmente poderosa e complexa, e sua ligação com Ciri, uma jovem com um destino misterioso e um poder inestimável, acrescentam camadas de profundidade emocional à narrativa.\r\nEnquanto Geralt caça monstros e desvenda conspirações, ele também explora temas universais como amor, ódio, redenção e sacrifício. A trama densa e os diálogos ricos proporcionam uma imersão única em um mundo onde cada escolha tem consequências, e onde nenhum segredo permanece enterrado para sempre.\r\nEm suma, The Witcher transcende a mera fantasia para se tornar uma saga épica que cativa pela complexidade de seus personagens, a profundidade de seu mundo e a habilidade de suas histórias em capturar a imaginação dos jogadores. Em meio a feitiçarias e espadas, Geralt de Rivia se destaca como um herói relutante, moldado pelas circunstâncias de um mundo onde o mal muitas vezes reside não apenas nos monstros, mas também nos corações dos homens.', 'Carlos Miguel Oliveira', '2024-06-26');

-- --------------------------------------------------------

--
-- Estrutura para tabela `users`
--

CREATE TABLE `users` (
  `id` int(11) NOT NULL,
  `name` varchar(255) NOT NULL,
  `email` varchar(255) NOT NULL,
  `password` varchar(255) NOT NULL,
  `cpf` varchar(255) NOT NULL,
  `phone` varchar(255) NOT NULL,
  `isAdmin` tinyint(1) DEFAULT 0
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

--
-- Despejando dados para a tabela `users`
--

INSERT INTO `users` (`id`, `name`, `email`, `password`, `cpf`, `phone`, `isAdmin`) VALUES
(1, 'Admin', 'admin@example.com', 'password', '123.123.123-12', '(21) 34413-1676', 1),
(2, 'José Pereira Santos', 'jose@example.com', 'password', '457.584.326-87', '(45) 43575-6853', 0),
(3, 'Débora Ribeiro Nunes', 'deb@example.com', 'password', '926.730.956-44', '(12) 53563-4673', 0),
(4, 'Vanessa Soares', 'soares_vanessa@example.com', 'password', '872.359.740-99', '(11) 63264-8126', 0),
(5, 'Carlos Miguel Oliveira', 'carlim@example.com', 'password', '214.125.345-53', '(31) 34536-4356', 0),
(6, 'Maria Souza Nascimento', 'nasc@example.com', 'password', '125.678.075-64', '(09) 12352-7415', 0),
(7, 'Jonas Espíndola', 'jonas@example.com', 'password', '346.508.934-59', '(56) 36785-7858', 0),
(8, 'Sara Mendes Garcia', 'sara_mendes@example.com', 'password', '453.265.604-30', '(53) 62256-7245', 0),
(9, 'Cristiano Matos Cardoso', 'cr7@example.com', 'password', '340.564.705-46', '(61) 45236-3265', 0),
(10, 'Camila Peixoto', 'camila@example.com', 'password', '372.794.280-93', '(34) 68634-6873', 0);

--
-- Índices para tabelas despejadas
--

--
-- Índices de tabela `posts`
--
ALTER TABLE `posts`
  ADD PRIMARY KEY (`id`);

--
-- Índices de tabela `users`
--
ALTER TABLE `users`
  ADD PRIMARY KEY (`id`);

--
-- AUTO_INCREMENT para tabelas despejadas
--

--
-- AUTO_INCREMENT de tabela `posts`
--
ALTER TABLE `posts`
  MODIFY `id` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=11;

--
-- AUTO_INCREMENT de tabela `users`
--
ALTER TABLE `users`
  MODIFY `id` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=11;
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
